name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      run:
        sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/libgtest.a /usr/lib  && sudo cp lib/libgtest_main.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
        sudo apt-get install libbenchmark-dev
    
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: 
        # ./test/optimize_nn
        ./test/test_binary_container
        ./test/test_binary_container_cmp
        ./test/test_nn
        ./test/test_nn_golden
        ./test/container/container100
        ./test/container/container128
        ./test/container/container200
        ./test/container/container256
        ./test/container/container40
        ./test/container/container64
        ./test/distribution/dist_nn_golden_100
        ./test/distribution/dist_nn_golden_128
        ./test/distribution/dist_nn_golden_200
        ./test/distribution/dist_nn_golden_250
        ./test/distribution/dist_nn_golden_256
        ./test/distribution/dist_nn_golden_40
        ./test/distribution/dist_nn_golden_64
        ./test/nn/nn_golden_100
        ./test/nn/nn_golden_128
        ./test/nn/nn_golden_200
        ./test/nn/nn_golden_250
        ./test/nn/nn_golden_256
        ./test/nn/nn_golden_32
        ./test/nn/nn_golden_40
        ./test/nn/nn_golden_64
        
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Benchmark library
        uses: actions/cache@v1
        with:
          path: bench
          key: ${{ runner.os }}-googlebenchmark-v1.5.0

      - name: Run benchmark
        run: ./a.out --benchmark_format=json | tee benchmark_result.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: bench/benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@FloydZ'
